import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './../globals.css';
import { LoginHeader } from '@/components/LoginHeader';
import { LoginMain } from '@/components/LoginMain';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout() {
  return (
    <div className='bg-primary h-full '>
      <LoginHeader />
      <LoginMain />
    </div>
  );
}
